export type GitHubQuery = {
  name: string;
  query: string;
  limit: number;
};

export type BountyPlatform = "algora" | "polar" | "issuehunt" | "gitcoin";

export type OnboardingAnswers = {
  minimumAmountUsd: number;
  preferredAmountUsd: number;
  maxActiveBounties: number;
  maxResearchMinutesBeforeDecision: number;
  maxExpectedFixHours: number;
  defaultDecisionThreshold: number;
  prefer: string[];
  avoid: string[];
  requireExplicitPayout: boolean;
  requireOpenIssue: boolean;
  requireNoExistingSolvingPr: boolean;
  requireUserApprovalBeforeClaiming: boolean;
  requireUserApprovalBeforePosting: boolean;
  githubQueries: GitHubQuery[];
  enabledPlatforms: BountyPlatform[];
  includeRepos: string[];
  excludeRepos: string[];
  includeLanguages: string[];
  excludeLanguages: string[];
  minimumSearchAmountUsd: number;
};

export type WritePolicy = "preserve" | "overwrite";
export type WritePlan = { action: "skip" | "write"; path: string };

export function defaultOnboardingAnswers(): OnboardingAnswers {
  return {
    minimumAmountUsd: 100,
    preferredAmountUsd: 500,
    maxActiveBounties: 1,
    maxResearchMinutesBeforeDecision: 30,
    maxExpectedFixHours: 12,
    defaultDecisionThreshold: 18,
    prefer: [
      "small reproducible bugs",
      "failing tests with clear expected behavior",
      "CLI/tooling fixes",
      "TypeScript/JavaScript/Python issues",
      "docs only when acceptance criteria are explicit",
    ],
    avoid: [
      "unclear payout terms",
      "already crowded issues",
      "maintainers inactive for 30+ days",
      "issues requiring large rewrites before payout",
      "speculative feature requests without maintainer buy-in",
    ],
    requireExplicitPayout: true,
    requireOpenIssue: true,
    requireNoExistingSolvingPr: true,
    requireUserApprovalBeforeClaiming: true,
    requireUserApprovalBeforePosting: true,
    githubQueries: [
      { name: "explicit-bounty-label", query: "is:issue is:open label:bounty", limit: 50 },
      { name: "bounty-in-title", query: "is:issue is:open bounty in:title", limit: 50 },
      { name: "reward-in-body", query: "is:issue is:open reward bounty in:body", limit: 50 },
      { name: "funded-good-first-issue", query: 'is:issue is:open "good first issue" bounty', limit: 50 },
    ],
    enabledPlatforms: ["algora", "polar", "issuehunt"],
    includeRepos: [],
    excludeRepos: [],
    includeLanguages: [],
    excludeLanguages: [],
    minimumSearchAmountUsd: 0,
  };
}

export function mergeOnboardingAnswers(overrides: Partial<OnboardingAnswers>): OnboardingAnswers {
  return { ...defaultOnboardingAnswers(), ...overrides };
}

export function planConfigWrite(path: string, exists: boolean, policy: WritePolicy): WritePlan {
  if (exists && policy === "preserve") return { action: "skip", path };
  return { action: "write", path };
}

export function buildStrategyConfig(answers: OnboardingAnswers): string {
  return `# Generated by bounty-ops onboarding. Re-run \`bun run setup\` or ask \`/bounty-ops onboard\` to update.

bounty_strategy:
  minimum_amount_usd: ${answers.minimumAmountUsd}
  preferred_amount_usd: ${answers.preferredAmountUsd}
  max_active_bounties: ${answers.maxActiveBounties}
  max_research_minutes_before_decision: ${answers.maxResearchMinutesBeforeDecision}
  max_expected_fix_hours: ${answers.maxExpectedFixHours}
  default_decision_threshold: ${answers.defaultDecisionThreshold}

work_preferences:
  prefer:
${yamlList(answers.prefer, 4)}
  avoid:
${yamlList(answers.avoid, 4)}

risk_policy:
  require_explicit_payout: ${answers.requireExplicitPayout}
  require_open_issue: ${answers.requireOpenIssue}
  require_no_existing_solving_pr: ${answers.requireNoExistingSolvingPr}
  require_user_approval_before_claiming: ${answers.requireUserApprovalBeforeClaiming}
  require_user_approval_before_posting: ${answers.requireUserApprovalBeforePosting}
`;
}

export function buildSearchConfig(answers: OnboardingAnswers): string {
  return `# Generated by bounty-ops onboarding. Re-run \`bun run setup\` or ask \`/bounty-ops onboard\` to update.

github_issue_queries:
${answers.githubQueries.map(formatQuery).join("\n")}

bounty_platforms:
${formatPlatform("algora", answers.enabledPlatforms, "web")}
${formatPlatform("polar", answers.enabledPlatforms, "web")}
${formatPlatform("issuehunt", answers.enabledPlatforms, "web")}
${formatPlatform("gitcoin", answers.enabledPlatforms, "web3_optional")}

filters:
  include_repos:
${yamlList(answers.includeRepos, 4)}
  exclude_repos:
${yamlList(answers.excludeRepos, 4)}
  include_languages:
${yamlList(answers.includeLanguages, 4)}
  exclude_languages:
${yamlList(answers.excludeLanguages, 4)}
  minimum_amount_usd: ${answers.minimumSearchAmountUsd}
`;
}

function formatQuery(query: GitHubQuery): string {
  return `  - name: ${query.name}\n    query: '${escapeSingleQuoted(query.query)}'\n    limit: ${query.limit}`;
}

function formatPlatform(platform: BountyPlatform, enabledPlatforms: BountyPlatform[], discovery: string): string {
  return `  ${platform}:\n    enabled: ${enabledPlatforms.includes(platform)}\n    discovery: ${discovery}`;
}

function yamlList(values: string[], indent: number): string {
  const spaces = " ".repeat(indent);
  if (values.length === 0) return `${spaces}[]`;
  return values.map((value) => `${spaces}- ${value}`).join("\n");
}

function escapeSingleQuoted(value: string): string {
  return value.replaceAll("'", "''");
}
